### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jendap** [reactiveai/cloud-vision-explorer#304]
What license is this code, please?

Can we add a LICENSE file to the repo?

**Comment by raynux** [comment]
Hi @jendap. It's `Apache License v2`. Sure, I'm gonna add one.

**Comment by raynux** [comment]
closing with c734042e0a800a629c04483bb36f4c6c341a282f

**Comment by jendap** [comment]
Perfect. Good choice!

Thank you!
