### ISSUE TITLE
Local galaxy

### ISSUE THREAD

**Issue by jrabary** [reactiveai/cloud-vision-explorer#306]
Thank you for opening this great tools ! I'm wondering whether it's possible to generate and use a "local" galaxy data without using google cloud storage for an offline demo purpose ?

**Comment by nickjanssen** [comment]
Hi @jrabary, you can yes. Simply change `DATAPOINT_URL` at the top of `RenderView.js` to point to a local url, like `output.json` and make sure `output.json` is in your `public` folder.

**Comment by jrabary** [comment]
Thank you @nickjanssen. Is the format of the output.json documented elsewhere ?

**Comment by nickjanssen** [comment]
I've just added a section to [this wiki page](https://github.com/reactiveai/cloud-vision-explorer/wiki/How-to-build-your-own-galaxy) explaining the format of `output.json`, let me know if that helps!
