### ISSUE TITLE
can you explain how to deploy the keam.py to the GCP?

### ISSUE THREAD

**Issue by bearprada** [reactiveai/cloud-vision-explorer#311]
Hi, I'm very interesting about this demo. especially the running the k-mean algorithm on the GCP.

is it publish yet? i think it might be this server.

https://cloud.google.com/ml/

this page only tell me running the script locally 
https://github.com/reactiveai/cloud-vision-explorer/wiki/Model

**Comment by raynux** [comment]
Hi @bearprada 
Though we are very interested in Cloud ML, all the calculation is done locally at the moment.
https://github.com/reactiveai/cloud-vision-explorer/blob/master/ml-libs/clustering/kmeans.py
